title: Programacion Genetica paso a paso
tagline: Todo lo que deseas saber acerca del método de búsqueda más prometedor.
description: Aprende a configurar, ejecutar e interpretar el algoritmo de busqueda de programacion genetica paso a paso.

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: GP-on-github
  repo: GP-template

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: Python # the type of action, full list at https://lab.github.com/docs/actions/
  # some actions require additional options, those should appear below `type:`
  # you can execute multiple actions in the `before` block

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: EDIT HERE - INTERNAL COMMENT DESCRIBING STEP 
- title: Introduccion
  description: En esta seccion encontraras la teoría necesaria para comprenden de donde proviene Programación Genetica, los conceptos principales, sus usos y por supuesto las hacía donde se dirige.
  #event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  #actions: # a list of the actions that will occur when the step is triggered by an event
  #- type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 2: EDIT HERE -INTERNAL COMMENT FOR STEP 2
# - title: # the title of the step, shown to the learner in the course progress page
#  description: # a description of the step, shown to the learner in the course progress page
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 3: EDIT HERE - INTERNAL COMMENT FOR STEP 3
# - title: # the title of the step, shown to the learner in the course progress page
#  description: # a description of the step, shown to the learner in the course progress page
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 4: EDIT HERE - INTERNAL COMMENT FOR STEP 4
# - title: # the title of the step, shown to the learner in the course progress page
#  description: # a description of the step, shown to the learner in the course progress page
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 5: EDIT HERE - INTERNAL COMMENT FOR STEP 5
# - title: # the title of the step, shown to the learner in the course progress page
#  description: # a description of the step, shown to the learner in the course progress page
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

